name: CI

on:
  push:
    branches: [main, develop, feat/**, fix/**]
  pull_request:
    branches: [main, develop, feat/**, fix/**]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run typecheck
      - name: Run tests
        run: npm run test:ci
      - name: Output coverage report
        if: always()
        run: |
          if [ -f coverage/lcov-report/index.html ]; then
            echo "Coverage report generated at coverage/lcov-report/index.html"
          else
            echo "No coverage report found."
          fi
